#!/bin/bash  
 
# First argument: Client identifier  
 
KEY_DIR=/etc/openvpn/easy-rsa/keys  
OUTPUT_DIR=~/client-configs/files  
BASE_CONFIG=~/client-configs/base.conf  
  
cat ${BASE_CONFIG} \  
    <(echo -e '<ca>') \  
    ${KEY_DIR}/ca.crt \  
    <(echo -e '</ca>\n<cert>') \  
    ${KEY_DIR}/<span style="color:#FF0000;">client1</span>.crt \  
    <(echo -e '</cert>\n<key>') \  
    ${KEY_DIR}/<span style="color:#FF0000;">client1</span>.key \  
    <(echo -e '</key>\n<tls-auth>') \  
    ${KEY_DIR}/ta.key \  
    <(echo -e '</tls-auth>') \  
    > ${OUTPUT_DIR}/${1}.ovpn  
